#2swagger
homahi/keijiban20180403 pull request #11
Opened 2018-04-04 22:02 UTC by homahi

見て欲しいとこ、
・yamlの置き場所はここで良い？
・swaggerの内容を見る方法を次作るのがよい？
・他何かあれば

2018-04-04 22:08 UTC, homahi commented
今はとりあえずローカルでswagger-uiでも適当に叩いて見てって感じではあるな。

2018-04-04 22:27 UTC, kazuma1989 requested changes

2018-04-04 22:27 UTC, kazuma1989 commented on swagger.yml
> +      properties:
exampleがほしい。

2018-04-05 22:07 UTC, kazuma1989 commented
#18

2018-04-05 22:07 UTC, kazuma1989 commented on swagger.yml
> +      properties:
#18

2018-04-05 22:17 UTC, kazuma1989 approved these changes

2018-04-05 22:19 UTC, merged