#24date
homahi/keijiban20180403 pull request #32
Opened 2018-04-10 21:53 UTC by ObayashiTatsunori

2018-04-10 21:59 UTC, homahi requested changes

2018-04-10 21:59 UTC, homahi commented on keijiban-api/index.js
> +          createdAt:date
createの後もresponseを返すようにして欲しい。
今だとcurlとかで叩くとresponseが帰って来ないので応答待ちになる。

2018-04-10 22:00 UTC, homahi requested changes

2018-04-10 22:00 UTC, homahi commented on keijiban-api/index.js
> +      var createdate = dateformat(list.createdAt, 'yyyy年mm月dd日 HH時MM分ss秒');
日付フォーマットはISO8601が良いのではないか（標準なので

https://qiita.com/kidatti/items/272eb962b5e6025fc51e

2018-04-10 22:06 UTC, kazuma1989 approved these changes

2018-04-11 21:59 UTC, homahi requested changes

2018-04-11 21:59 UTC, homahi commented on keijiban-api/index.js
> +      var item = {id:list.id,contributor:list.contributor,body:list.body,createdate:createdate};
createdate -> createdAt にしよう。

2018-04-11 22:01 UTC, homahi approved these changes

2018-04-11 22:01 UTC, merged